version: 2

before:
  hooks:
    - go mod tidy

builds:
  - ldflags:
      - -w -s -X github.com/jsthtlf/usql/text.CommandVersion={{.Version}}
  - goos:
      - linux
      - darwin

archives:
  - formats: [tar.gz]
    name_template: "{{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
