// Package internal provides a way to obtain information about which database
// drivers were included at build.
package internal

// Code generated by gen.go. DO NOT EDIT.

// KnownBuildTags returns a map of known driver names to its respective build
// tags.
func KnownBuildTags() map[string]string {
	return map[string]string{
		"clickhouse": "clickhouse", // github.com/ClickHouse/clickhouse-go/v2
		"mysql":      "mysql",      // github.com/go-sql-driver/mysql
		"oracle":     "oracle",     // github.com/sijms/go-ora/v2
		"pgx":        "pgx",        // github.com/jackc/pgx/v5/stdlib
		"postgres":   "postgres",   // github.com/lib/pq
		"sqlserver":  "sqlserver",  // github.com/microsoft/go-mssqldb
	}
}
